language: node_js
node_js:
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.8"
  - "5.12"
  - "6.11"
  - "7.10"
  - "8.4"
script:
  - npm run test_ci
#The coveralls@2.10.0 version supported node < 4.x
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"